[package]
name = "application-a"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.8"
hello = { path = "imports/shared-libs/crates/hello" }
logging = { path = "imports/shared-libs/crates/logging" }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "postgres", "migrate", "macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "time"] }
tracing = "0.1"
